
import Foundation

struct Deck {
    let cards: [Card]
    static let defaultDeck = [
        Card(prompt:"Think about someone in your life that is no longer here. What is one lesson they taught you?"),
        Card(prompt:"What are you excited to go home to?"),
        Card(prompt:"What do you know about yourself now that you didn't when you were younger"),
        Card(prompt:"Do I seem like I'm good at embracing my insecurities?"),
        Card(prompt:"I could improve my relationship with the Qur'an by _."),
        Card(prompt:"Tell me something about your mother that you didn't appreciate until you became older."),
        Card(prompt:"Tell me something about your father that you didn't appreciate until you became older."),
        Card(prompt:"Tell me something about you that less than 5 people know."),
        Card(prompt:"What steps could you take today to get closer to Allah?"),
        Card(prompt:"What are you not being honest with yourself about?"),
        Card(prompt:"Do I seem like I need validation?"),
        Card(prompt:"Describe your ultimate cheat meal."),
        Card(prompt:"Run me through what you've felt in each part of today."),
        Card(prompt:"Who is someone you're thankful to? Let's come up with a meaningful gift you could get them."),
        Card(prompt:"Name one thing you love about the way you've been raised."),
        Card(prompt:"How can I help?"),
        Card(prompt:"Who haven't you connected with in a long time? Call them."),
        Card(prompt:"Tell me one of your anxieties/worries. Let's talk it out."),
        Card(prompt:"Are you a defensive person?"),
        Card(prompt:"Do you need to forgive yourself more easily?"),
        Card(prompt:"Do you find it easy to apologise?"),
        Card(prompt:"Who inspired you the most in your childhood? Do they still inspire you now?"),
        Card(prompt:"How can you improve your relationship with your parents?"),
        Card(prompt:"If someone could see your actions and not hear your words, what would they say your priorities are?"),
        Card(prompt:"What do you want me to take the lead on?"),
        Card(prompt:"What does a perfect night in look like to you?"),
        Card(prompt:"What are you overthinking?"),
        Card(prompt:"What is the biggest small thing that you could do today?"),
        Card(prompt:"When was the last time you spoke from your heart to Allah? What motivated it?"),
        Card(prompt:"Do you think I'm good at hiding my emotions?"),
        Card(prompt:"Do you think I'm reaching my potential?"),
        Card(prompt:"If you were to start a new business today what would it be?"),
        Card(prompt:"One of Allah's names is 'Your Protecting Friend'. Name a time in your life where you have fest that name in existence."),
        Card(prompt:"What are you most thankful to Allah for this week?"),
        Card(prompt:"Do you think I find it hard to empathise?"),
        Card(prompt:"What motivates you to get out of bed every morning?"),
        Card(prompt:"Do I seem like more of a doer or a thinker?"),
        Card(prompt:"When was the last time you laughed so hard your stomach hurt?"),
        Card(prompt:"What about me intimidates you the most?"),
        Card(prompt:"How can we improve our relationship?"),
        Card(prompt:"In the past year, what was the moment in which you felt closest to Allah?"),
        Card(prompt:"What about keeping in touch with people do you find the hardest?"),
        Card(prompt:"What are you avoiding lately? Why?"),
        Card(prompt:"What do you do daily to exercise your mental health?"),
        Card(prompt:"When I think of meeting Allah, I feel _."),
        Card(prompt:"Finish the sentence: When I am (double your age), I would like to be _."),
        Card(prompt:"What does patience mean to you?"),
        Card(prompt:"My biggest insecurity is _."),
        Card(prompt:"How do you deal with pressure?"),
        Card(prompt:"What do you think the hardest part of my childhood was?"),
        Card(prompt:"Finish the sentence: Dear Allah, _."),
        Card(prompt:"How could you be better with your finances?"),
        Card(prompt:"One of Allah's names is the 'The Subtle'. Do you remember the moment that shaped your life as you know it?"),
        Card(prompt:"What's your best memory with me?"),
        Card(prompt:"Who really are you?"),
        Card(prompt:"When was the last time you lost track of time?"),
        Card(prompt:"What was a point in your life when you started believing in yourself?"),
        Card(prompt:"What's a win you could really do with right now? Why?"),
        Card(prompt:"What are you most thankful to Allah for this week?"),
        Card(prompt:"Tell me an Islamic reminder you once heard that has stayed with you to this day."),
        Card(prompt:"When was the last time you faced a fear? How did you feel afterwards?"),
        Card(prompt:"If you could give me a piece of advice on anything what would it be?"),
        Card(prompt:"Think about someone you recently had a disagreement with. Without telling me who they are, share 3 amazing qualities about them."),
        Card(prompt:"What is weighing heavy on your heart right now?"),
        Card(prompt:"What life question have you recently found an answer for?"),
        Card(prompt:"What took you the longest to understand about me?"),
        Card(prompt:"Ask me anything. I promise to be vulnerable."),
        Card(prompt:"What's your routine when you're angry?"),
        Card(prompt:"What's been thought about today?"),
        Card(prompt:"What keeps you balanced?"),
        Card(prompt:"What are you preventing yourself from feeling?"),
        Card(prompt:"Who makes you feel safe?"),
        Card(prompt:"Do you think I am where I want to be in life?"),
        Card(prompt:"Would you say that you are the same person in private as you are in public?"),
        Card(prompt:"Who is your biggest cheerleader?")
    ]
}

struct Card: Hashable {
    let prompt: String

    static let example = Card(prompt: "What are you excited to go home to?")
}
